// <auto-generated />
namespace UpFit__main.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedmeal2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmeal2));
        
        string IMigrationMetadata.Id
        {
            get { return "202305251246528_addedmeal2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
